### ISSUE TITLE
Change jar packaging logic to allow transitive dependency

### ISSUE THREAD

**Issue by RomChig** [wannesvr/dota2api#1]
@wannesvr Hello, so, using the current approach to package into the jar you've lost the ability to use your lib in runtime with dependent transitive libs, e.g. Lombok uses logging dependency inside, and this dependency isn't seen by the classloader of the app which uses your lib. Please add packaging **"jar-with-dependencies"**, thanks beforehand.

Unfortunately can't push the branch in order to create a pull request.

**Comment by wannesvr** [comment]
@RomChig Hi Roman, I've created a pull request: #2 
Can you confirm this fixes your issue?

I'll see if I can open the repository so you can create any future PR's.
I'm not really actively updating this library anymore but I'm willing to try and fix issues/enhancements if you notice any.

**Comment by RomChig** [comment]
@wannesvr I checked, it works.
Thank you
