### ISSUE TITLE
Problem with mapping an obj from json to java.sql.Time 

### ISSUE THREAD

**Issue by RomChig** [wannesvr/dota2api#17]
@wannesvr - Hi, Van, trying to get match details by specific match_id - seeing the issue _"Couldn't parse JSON to com.github.wannesvr.core.model.match.MatchDetail"_  after looking more inside found some problems with mapping, 

Steps to reproduce: 
1. You need to have private static final String API_KEY = "someKey here"
2. You need to have private static final long MATCH_ID = "someSpecific match_id here"
3. execute such code -> 
```
Dota2ApiClient client = new Dota2ApiClient(API_KEY);
MatchDetailRequest matchDetailRequest = new MatchDetailRequest.Builder(MATCH_ID).build();
MatchDetail matchDetail = client.send(matchDetailRequest);
System.out.println(matchDetail);
```

**detailMessage :**
_Cannot construct instance of java.sql.Time (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1013)
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.github.wannesvr.core.model.match.MatchDetail["duration"])_
 
 Possible solutions seem without influence for other parts of the app:
 1. use long type instead of java.sql.Time -> in MatchDetail class will be the field: 
 ```
@JsonProperty("duration")
 private long duration;
```
after that easily can be transformed to the needed type using e.g TimeUnit:
`TimeUnit.SECONDS.toMinutes(matchDetail.getDuration())`

2. use java. util.Date instead of java.sql.Time

```
@JsonProperty("duration")
 private Date duration;
```
in this case, we're able to parse this value to the relevant format as well 

In my mind, the first approach is better. What do u think?

**Comment by wannesvr** [comment]
I'm fine with using the `long` approach since IIRC it just shows the amount of seconds since match start. 
I've fixed this in #18. You can close this if your issue is solved

**Comment by wannesvr** [comment]
I also added the `Throwable` constructor to the Dota2ApiException which should help you in case parsing errors occur in the future.

**Comment by RomChig** [comment]
@wannesvr - thanks
