### ISSUE TITLE
The quantity of heros is out of bounds

### ISSUE THREAD

**Issue by RomChig** [wannesvr/dota2api#19]
Hi @wannesvr 
I'm gonna get the hero by id  e.g. 130, and catch " index out of bounds ex" cause, you store heroId's in byte[-128; 127], amount heroes id is more than 127. There is a class Hero -> heroId field 
**MatchDetailPlayer** class
```
@JsonProperty("hero_id")
private byte heroId;
```

Could we exchange that with e.g. int type?

**Comment by wannesvr** [comment]
Hahah, a reminder from when dota still had less heroes. I’ll fix it!

**Comment by wannesvr** [comment]
fixed on master
