### ISSUE TITLE
Incorrect years inside startTime values

### ISSUE THREAD

**Issue by RomChig** [wannesvr/dota2api#24]
@wannesvr Hi 👋🏻
For some reason, we see the wrong start match date in a particular year, it is 1970y
Example of some startTime match value: `Tue Jan 20 00:18:17 EET 1970`

**Comment by wannesvr** [comment]
Hi, I've changed the datetype to use the newer `Instant` class which was added in Java 8. Because this is a breaking change I've updated the version to [2.0.0](https://mvnrepository.com/artifact/io.github.wannesvr/Dota2ApiWrapper) and uploaded this so you should be able to use it.

**Comment by RomChig** [comment]
Yes, it works nice, thanks!
